"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import api from "@/lib/axios";
import TripCard from "@/components/TripCard";
import { Loader2, ArrowLeft, Printer, Share2 } from "lucide-react";
import Button from "@/components/UI/Button";

export default function SingleTripPage() {
  const { id } = useParams();
  const router = useRouter();
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchTripDetails = async () => {
      try {
        const { data } = await api.get(`/trips/${id}`);
        setTrip(data);
      } catch (err) {
        console.error("Error fetching trip details:", err);
        // If trip doesn't exist or unauthorized, send back to dashboard
        router.push("/trips");
      } finally {
        setLoading(false);
      }
    };

    if (id) fetchTripDetails();
  }, [id, router]);

  const handlePrint = () => window.print();

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <Loader2 className="h-10 w-10 text-blue-600 animate-spin mx-auto mb-4" />
          <p className="text-gray-500 font-medium">
            Retrieving your itinerary...
          </p>
        </div>
      </div>
    );
  }

  if (!trip) return null;

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      {/* Action Bar */}
      <div className="bg-white border-b border-gray-100 sticky top-16 z-40 print:hidden">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <button
            onClick={() => router.back()}
            className="flex items-center gap-2 text-gray-600 hover:text-blue-600 font-medium transition-colors"
          >
            <ArrowLeft size={20} /> Back
          </button>

          <div className="flex gap-3">
            <button
              onClick={handlePrint}
              className="p-2.5 text-gray-500 hover:bg-gray-100 rounded-xl transition-all"
              title="Print Trip"
            >
              <Printer size={20} />
            </button>
            <button
              className="p-2.5 text-gray-500 hover:bg-gray-100 rounded-xl transition-all"
              title="Share Link"
              onClick={() => {
                navigator.clipboard.writeText(window.location.href);
                alert("Link copied to clipboard!");
              }}
            >
              <Share2 size={20} />
            </button>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="max-w-7xl mx-auto px-4 pt-8 md:pt-12">
        {/* We map the Database fields back to the TripCard prop format */}
        <TripCard
          trip={{
            ...trip,
            hotelRecommendations: trip.hotelOptions, // Match UI key to DB key
            flightRecommendations: trip.flightDetails,
            tripSummary: {
              destination: trip.destination,
              totalGroupSize: trip.groupSize,
              duration: trip.duration,
              budgetTier: trip.budget,
            },
          }}
        />
      </div>

      {/* Print-only Footer */}
      <div className="hidden print:block text-center text-gray-400 text-xs mt-10 italic">
        Generated by AI Travel Planner — Adventure Awaits.
      </div>
    </div>
  );
}
